services:
  production-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8080:18888"
    expose:
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  keycloak:
    image: "quay.io/keycloak/keycloak:26.3"
    command:
      - "start"
      - "--import-realm"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
      VIRTUAL_HOST: "id.overflow.local"
      VIRTUAL_PORT: "8080"
    expose:
      - "8080"
      - "9000"
    volumes:
      - type: "volume"
        target: "/opt/keycloak/data"
        source: "keycloak-data"
        read_only: false
      - type: "bind"
        target: "/opt/keycloak/data/import"
        source: "C:\\Developer\\Courses\\Overflow\\infa\\realms"
        read_only: true
    networks:
      - "aspire"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "postgres-data"
        read_only: false
    networks:
      - "aspire"
  typesense:
    image: "typesense/typesense:29.0"
    command:
      - "--data-dir"
      - "/data"
      - "--api-key=xyz"
      - "--enable-cors"
    expose:
      - "8108"
    volumes:
      - type: "volume"
        target: "/data"
        source: "typesense-data"
        read_only: false
    networks:
      - "aspire"
  messaging:
    image: "docker.io/library/rabbitmq:4.1-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${MESSAGING_PASSWORD}"
    expose:
      - "5672"
      - "15672"
    volumes:
      - type: "volume"
        target: "/var/lib/rabbitmq"
        source: "rabbitmq-data"
        read_only: false
    networks:
      - "aspire"
  question-svc:
    image: "${QUESTION_SVC_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${QUESTION_SVC_PORT}"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      ConnectionStrings__questiondb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=questiondb"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "question-svc"
    expose:
      - "${QUESTION_SVC_PORT}"
    depends_on:
      keycloak:
        condition: "service_started"
      postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  profile-svc:
    image: "${PROFILE_SVC_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${PROFILE_SVC_PORT}"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      ConnectionStrings__profileDb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=profileDb"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "profile-svc"
    expose:
      - "${PROFILE_SVC_PORT}"
    depends_on:
      keycloak:
        condition: "service_started"
      postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  stat-svc:
    image: "${STAT_SVC_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${STAT_SVC_PORT}"
      ConnectionStrings__statDb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=statDb"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "stat-svc"
    expose:
      - "${STAT_SVC_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  search-svc:
    image: "${SEARCH_SVC_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SEARCH_SVC_PORT}"
      services__typesense__typesense__0: "http://typesense:8108"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "search-svc"
    expose:
      - "${SEARCH_SVC_PORT}"
    depends_on:
      messaging:
        condition: "service_started"
      typesense:
        condition: "service_started"
    networks:
      - "aspire"
  vote-svc:
    image: "${VOTE_SVC_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${VOTE_SVC_PORT}"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      ConnectionStrings__voteDb: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=voteDb"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "vote-svc"
    expose:
      - "${VOTE_SVC_PORT}"
    depends_on:
      keycloak:
        condition: "service_started"
      postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  gateway:
    image: "mcr.microsoft.com/dotnet/nightly/yarp:2.3.0-preview.4"
    command:
      - "/app/yarp.dll"
    entrypoint:
      - "dotnet"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      services__question-svc__http__0: "http://question-svc:${QUESTION_SVC_PORT}"
      REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/questions/{**catch-all}"
      REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_question-svc"
      REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/test/{**catch-all}"
      REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_question-svc"
      REVERSEPROXY__ROUTES__route2__MATCH__PATH: "/tags/{**catch-all}"
      REVERSEPROXY__ROUTES__route2__CLUSTERID: "cluster_question-svc"
      REVERSEPROXY__ROUTES__route3__MATCH__PATH: "/search/{**catch-all}"
      REVERSEPROXY__ROUTES__route3__CLUSTERID: "cluster_search-svc"
      REVERSEPROXY__ROUTES__route4__MATCH__PATH: "/profiles/{**catch-all}"
      REVERSEPROXY__ROUTES__route4__CLUSTERID: "cluster_profile-svc"
      REVERSEPROXY__ROUTES__route5__MATCH__PATH: "/stats/{**catch-all}"
      REVERSEPROXY__ROUTES__route5__CLUSTERID: "cluster_stat-svc"
      REVERSEPROXY__ROUTES__route6__MATCH__PATH: "/votes/{**catch-all}"
      REVERSEPROXY__ROUTES__route6__CLUSTERID: "cluster_vote-svc"
      REVERSEPROXY__CLUSTERS__cluster_question-svc__DESTINATIONS__destination1__ADDRESS: "https+http://question-svc"
      REVERSEPROXY__CLUSTERS__cluster_search-svc__DESTINATIONS__destination1__ADDRESS: "https+http://search-svc"
      REVERSEPROXY__CLUSTERS__cluster_profile-svc__DESTINATIONS__destination1__ADDRESS: "https+http://profile-svc"
      REVERSEPROXY__CLUSTERS__cluster_stat-svc__DESTINATIONS__destination1__ADDRESS: "https+http://stat-svc"
      REVERSEPROXY__CLUSTERS__cluster_vote-svc__DESTINATIONS__destination1__ADDRESS: "https+http://vote-svc"
      services__search-svc__http__0: "http://search-svc:${SEARCH_SVC_PORT}"
      services__profile-svc__http__0: "http://profile-svc:${PROFILE_SVC_PORT}"
      services__stat-svc__http__0: "http://stat-svc:${STAT_SVC_PORT}"
      services__vote-svc__http__0: "http://vote-svc:${VOTE_SVC_PORT}"
      ASPNETCORE_URLS: "http://*:8001"
      VIRTUAL_HOST: "api.overflow.local"
      VIRTUAL_PORT: "8001"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway"
    ports:
      - "8001:8001"
    expose:
      - "5000"
    networks:
      - "aspire"
  webapp:
    image: "${WEBAPP_IMAGE}"
    environment:
      NODE_ENV: "production"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      PORT: "4000"
      VIRTUAL_HOST: "app.overflow.local"
      VIRTUAL_PORT: "4000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "webapp"
    expose:
      - "4000"
    networks:
      - "aspire"
  nginx-proxy:
    image: "nginxproxy/nginx-proxy:1.8"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: "bind"
        target: "/tmp/docker.sock"
        source: "/var/run/docker.sock"
        read_only: true
      - type: "bind"
        target: "/etc/nginx/certs"
        source: "C:\\Developer\\Courses\\Overflow\\infa\\devcerts"
        read_only: true
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  keycloak-data:
    driver: "local"
  postgres-data:
    driver: "local"
  typesense-data:
    driver: "local"
  rabbitmq-data:
    driver: "local"
